sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t pathmotion/drone-gcloud-cli-plugin .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master